version: '3'
services:
  forum-service:
    build: .
    image: forum-service:latest
    container_name: forum-service
    ports:
      - "8999:80"
    volumes:
      - "/workspace/project/IT_Forum:/app"
      - "/workspace/logs/IT_Forum:/var/log/uwsgi"
    environment:
      UWSGI_INI: /app/uwsgi.ini

    depends_on:
      - redis
  redis:
    images: redis
    ports:
     - "6379:6379"
