version: '3'
services:
  article-service:
    build: .
    image: forum-service:latest
    container_name: forum-service
    ports:
      - "8999:80"
    volumes:
      - "/workspace/project/IT-Forum:/app"
      - "/workspace/logs/IT-Forum:/var/log/uwsgi"

    environment:
      UWSGI_INI: /app/uwsgi.ini
